name:                cMajor
version:             0.1.0.0
github:              "pixlark/c-major"
license:             BSD3
author:              "pixlark"
maintainer:          "t1000.pixlark@gmail.com"
copyright:           "2021 pixlark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pixlark/c-major#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- mtl
- containers
- text

library:
  source-dirs: src

executables:
  cMajor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cMajor
