name:                cMajor
version:             0.1.0.0
github:              "pixlark/cMajor"
license:             BSD3
author:              "pixlark"
maintainer:          "cMajor@brooke2k.com"
copyright:           "2021 pixlark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pixlark/cMajor#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- megaparsec
- mtl
- optparse-applicative
- process
- regex-tdfa
- text
- json
- transformers
- filepath

library:
  source-dirs: src

executables:
  cMajor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cMajor
  cMajorTests:
    main:                Main.hs
    source-dirs:         test-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cMajor

